import 'dart:convert';
import 'dart:io';

const _entrypoint = 'tool/dom_first_stepper_entrypoint.dart';
const _generated = 'lib/src/renderer/seo_dom_first_stepper_runtime.g.dart';

Future<void> main(List<String> arguments) async {
  final write = arguments.contains('--write');
  if (arguments.any((argument) => argument != '--write')) {
    stderr.writeln('Usage: dart run tool/build_dom_first_stepper_runtime.dart '
        '[--write]');
    exitCode = 64;
    return;
  }

  final temp = await Directory.systemTemp.createTemp('esen-dom-first-stepper-');
  try {
    final output = '${temp.path}/stepper.js';
    final result = await Process.run(
      Platform.resolvedExecutable,
      [
        'compile',
        'js',
        '-O4',
        '--no-source-maps',
        '-o',
        output,
        _entrypoint,
      ],
      runInShell: false,
    );
    if (result.exitCode != 0) {
      stderr.write(result.stdout);
      stderr.write(result.stderr);
      exitCode = result.exitCode;
      return;
    }

    final javascript = await File(output).readAsString();
    if (javascript.toLowerCase().contains('</script') ||
        javascript.contains('<!--')) {
      stderr.writeln('Refusing a runtime containing unsafe inline code.');
      exitCode = 1;
      return;
    }
    final encoded = jsonEncode(javascript).replaceAll(r'$', r'\$');
    final unformattedSource =
        '// Generated by tool/build_dom_first_stepper_runtime.dart.\n'
        '// Do not edit by hand.\n'
        'const String seoDomFirstStepperRuntime = $encoded;\n';
    final sourceFile = File('${temp.path}/runtime.dart');
    await sourceFile.writeAsString(unformattedSource);
    final formatResult = await Process.run(
      Platform.resolvedExecutable,
      ['format', sourceFile.path],
      runInShell: false,
    );
    if (formatResult.exitCode != 0) {
      stderr.write(formatResult.stdout);
      stderr.write(formatResult.stderr);
      exitCode = formatResult.exitCode;
      return;
    }
    final source = await sourceFile.readAsString();
    final target = File(_generated);
    if (write) {
      await target.writeAsString(source);
      stdout.writeln('Wrote $_generated (${javascript.length} JS bytes).');
      return;
    }

    if (!target.existsSync() || await target.readAsString() != source) {
      stderr.writeln('$_generated is stale. Run this command with --write.');
      exitCode = 1;
      return;
    }
    stdout.writeln('DOM-first stepper runtime is current.');
  } finally {
    await temp.delete(recursive: true);
  }
}
