import 'dart:convert';
import 'dart:io';

import 'package:esen_seo/src/components/seo_theme_transition.dart';

const _generated = 'lib/src/renderer/seo_dom_first_theme_toggle_runtime.g.dart';

Future<void> main(List<String> arguments) async {
  final write = arguments.contains('--write');
  if (arguments.any((argument) => argument != '--write')) {
    stderr.writeln(
      'Usage: dart run tool/build_dom_first_theme_toggle_runtime.dart '
      '[--write]',
    );
    exitCode = 64;
    return;
  }

  const systemLight = SeoThemeState(systemIsDark: false);
  const systemDark = SeoThemeState(systemIsDark: true);
  final fromLight = transitionSeoTheme(
    systemLight,
    const SeoThemeToggleAction(),
  ).state.preference;
  final fromDark = transitionSeoTheme(
    systemDark,
    const SeoThemeToggleAction(),
  ).state.preference;
  final lightValue = serializeSeoThemePreference(SeoThemePreference.light)!;
  final darkValue = serializeSeoThemePreference(SeoThemePreference.dark)!;

  String js(String value) => jsonEncode(value);

  final javascript = '(()=>{'
      'let d=document,c=d.getElementById("esen-seo-content"),'
      'r=c&&c.querySelectorAll(\'[data-esen-component="theme-toggle"]\');'
      'if(!c||c.getAttribute("data-esen-seo-dom-first")!=="true"||'
      'd.querySelectorAll("#esen-seo-content").length!==1||r.length!==1)return;'
      'r=r[0];let g=n=>{let v=r.getAttribute(n);return v&&v.trim()},'
      'l=g("data-esen-light-label"),k=g("data-esen-dark-label"),'
      'L=g("data-esen-light-semantic-label"),'
      'K=g("data-esen-dark-semantic-label");'
      'if(r.tagName!=="SPAN"||!r.hasAttribute("hidden")||r.children.length||'
      'r.getAttribute("data-esen-enhanced")==="true"||'
      '[l,k,L,K].some(v=>!v||v.length>160))return;'
      'for(let e=r.parentElement;e&&e!==c;e=e.parentElement)'
      'if(e.hasAttribute("hidden")||e.hasAttribute("inert")||'
      '(e.getAttribute("aria-hidden")||"").trim().toLowerCase()==="true")return;'
      'let b=d.createElement("button"),m=matchMedia("(prefers-color-scheme: dark)"),'
      'S=${js(seoThemePreferenceStorageKey)},p="system",'
      'n={${js(lightValue)}:${js(serializeSeoThemePreference(fromLight)!)},'
      '${js(darkValue)}:${js(serializeSeoThemePreference(fromDark)!)}};'
      'try{let v=localStorage.getItem(S);if(v===${js(lightValue)}||'
      'v===${js(darkValue)})p=v}catch(_){}'
      'let a=()=>{let x=p===${js(darkValue)}||p==="system"&&m.matches,'
      'h=d.documentElement;p==="system"?h.removeAttribute("data-esen-theme"):'
      'h.setAttribute("data-esen-theme",p);b.textContent=x?l:k;'
      'b.dataset.esenDark=x;b.setAttribute("aria-label",x?L:K)};'
      'b.type="button";b.className="esen-seo-theme-toggle-button";'
      'b.onclick=()=>{let x=p===${js(darkValue)}||p==="system"&&m.matches;'
      'p=n[x?${js(darkValue)}:${js(lightValue)}];a();'
      'try{localStorage.setItem(S,p)}catch(_){}};'
      'r.append(b);r.removeAttribute("hidden");'
      'r.setAttribute("data-esen-enhanced","true");a();'
      'm.addEventListener("change",a);addEventListener("storage",e=>{'
      'if(e.key!==null&&e.key!==S)return;let v=e.newValue;'
      'p=v===${js(lightValue)}||v===${js(darkValue)}?v:"system";a()})'
      '})();';

  if (javascript.toLowerCase().contains('</script')) {
    stderr.writeln('Refusing a runtime containing a script end tag.');
    exitCode = 1;
    return;
  }
  final encoded = jsonEncode(javascript).replaceAll(r'$', r'\$');
  final unformattedSource =
      '// Generated by tool/build_dom_first_theme_toggle_runtime.dart.\n'
      '// Do not edit by hand.\n'
      'const String seoDomFirstThemeToggleRuntime = $encoded;\n';

  final temp = await Directory.systemTemp.createTemp('esen-theme-runtime-');
  try {
    final sourceFile = File('${temp.path}/runtime.dart');
    await sourceFile.writeAsString(unformattedSource);
    final formatResult = await Process.run(
      Platform.resolvedExecutable,
      ['format', sourceFile.path],
      runInShell: false,
    );
    if (formatResult.exitCode != 0) {
      stderr.write(formatResult.stdout);
      stderr.write(formatResult.stderr);
      exitCode = formatResult.exitCode;
      return;
    }
    final source = await sourceFile.readAsString();
    final target = File(_generated);
    if (write) {
      await target.writeAsString(source);
      stdout.writeln('Wrote $_generated (${javascript.length} JS bytes).');
      return;
    }
    if (!target.existsSync() || await target.readAsString() != source) {
      stderr.writeln('$_generated is stale. Run this command with --write.');
      exitCode = 1;
      return;
    }
    stdout.writeln('DOM-first theme toggle runtime is current.');
  } finally {
    await temp.delete(recursive: true);
  }
}
