import 'dart:convert';
import 'dart:io';

import 'package:esen_seo/src/components/seo_theme_transition.dart';

const _generated = 'lib/src/renderer/seo_dom_first_theme_toggle_runtime.g.dart';

Future<void> main(List<String> arguments) async {
  final write = arguments.contains('--write');
  if (arguments.any((argument) => argument != '--write')) {
    stderr.writeln(
      'Usage: dart run tool/build_dom_first_theme_toggle_runtime.dart '
      '[--write]',
    );
    exitCode = 64;
    return;
  }

  const systemLight = SeoThemeState(systemIsDark: false);
  const systemDark = SeoThemeState(systemIsDark: true);
  final fromLight = transitionSeoTheme(
    systemLight,
    const SeoThemeToggleAction(),
  ).state.preference;
  final fromDark = transitionSeoTheme(
    systemDark,
    const SeoThemeToggleAction(),
  ).state.preference;
  final lightValue = serializeSeoThemePreference(SeoThemePreference.light)!;
  final darkValue = serializeSeoThemePreference(SeoThemePreference.dark)!;
  final fromLightValue = serializeSeoThemePreference(fromLight)!;
  final fromDarkValue = serializeSeoThemePreference(fromDark)!;
  if (fromLightValue != darkValue || fromDarkValue != lightValue) {
    throw StateError('Theme toggle transition no longer flips the preference.');
  }

  String js(String value) => jsonEncode(value);

  final javascript = '(()=>{'
      'let d=document,C=d.querySelectorAll("#esen-seo-content"),c=C[0],'
      'R=c&&c.querySelectorAll(\'[data-esen-component="theme-toggle"]\');'
      'if(C.length!=1||c.dataset.esenSeoDomFirst!="true"||R.length!=1)return;'
      'let r=R[0],'
      'g=n=>(r.dataset[n]||"").trim(),'
      'l=g("esenLightLabel"),k=g("esenDarkLabel"),'
      'L=g("esenLightSemanticLabel"),K=g("esenDarkSemanticLabel");'
      'if(r.localName!="span"||!r.hidden||r.childElementCount||'
      'r.dataset.esenEnhanced=="true"||'
      '![l,k,L,K].every(v=>v&&v.length<161))return;'
      'for(let e=r;;e=e.parentElement){if(e.hasAttribute("inert")||'
      '/^\\s*true\\s*\$/i.test(e.getAttribute("aria-hidden")))return;'
      'if(e==c)break}'
      'let b=d.createElement("button"),m=matchMedia("(prefers-color-scheme: dark)"),'
      'S=${js(seoThemePreferenceStorageKey)},P=[${js(lightValue)},${js(darkValue)}],p,'
      'o=v=>{let i=P.indexOf(v);return i<0?null:!!i};'
      'try{p=o(localStorage.getItem(S))}catch(_){}'
      'let q=()=>p??m.matches,a=()=>{let x=q(),h=d.documentElement;'
      'if(p==null)delete h.dataset.esenTheme;else h.dataset.esenTheme=P[+p];'
      'b.textContent=x?l:k;'
      'b.dataset.esenDark=x;b.setAttribute("aria-label",x?L:K)};'
      'b.type="button";b.className="esen-seo-theme-toggle-button";'
      'b.onclick=()=>{p=!q();a();'
      'try{localStorage.setItem(S,P[+p])}catch(_){}};'
      'r.append(b);r.hidden=false;r.dataset.esenEnhanced="true";a();'
      'm.addEventListener("change",a);addEventListener("storage",e=>{'
      'if(e.key!=null&&e.key!=S)return;p=o(e.newValue);a()})'
      '})();';

  if (javascript.toLowerCase().contains('</script') ||
      javascript.contains('<!--')) {
    stderr.writeln('Refusing a runtime containing unsafe inline code.');
    exitCode = 1;
    return;
  }
  final encoded = jsonEncode(javascript).replaceAll(r'$', r'\$');
  final unformattedSource =
      '// Generated by tool/build_dom_first_theme_toggle_runtime.dart.\n'
      '// Do not edit by hand.\n'
      'const String seoDomFirstThemeToggleRuntime = $encoded;\n';

  final temp = await Directory.systemTemp.createTemp('esen-theme-runtime-');
  try {
    final sourceFile = File('${temp.path}/runtime.dart');
    await sourceFile.writeAsString(unformattedSource);
    final formatResult = await Process.run(
      Platform.resolvedExecutable,
      ['format', sourceFile.path],
      runInShell: false,
    );
    if (formatResult.exitCode != 0) {
      stderr.write(formatResult.stdout);
      stderr.write(formatResult.stderr);
      exitCode = formatResult.exitCode;
      return;
    }
    final source = await sourceFile.readAsString();
    final target = File(_generated);
    if (write) {
      await target.writeAsString(source);
      stdout.writeln('Wrote $_generated (${javascript.length} JS bytes).');
      return;
    }
    if (!target.existsSync() || await target.readAsString() != source) {
      stderr.writeln('$_generated is stale. Run this command with --write.');
      exitCode = 1;
      return;
    }
    stdout.writeln('DOM-first theme toggle runtime is current.');
  } finally {
    await temp.delete(recursive: true);
  }
}
